branches:
  only:
  - master
language: node_js
node_js:
  - lts/*
script: make -j
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
