branches:
  only:
  - master
language: node_js
node_js:
  - lts/*
script: make -j warmup TARGET_BRANCH=gh-pages && make -j
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: docs
  on:
    branch: master
